### ISSUE TITLE
Accuracy and Usage

### ISSUE THREAD

**Issue by aliyasineser** [sourishg/fisheye_stereo#3]
Thanks for the code. Helped me too much. I am trying to get disparity images from fisheye stereo pair. I calibrated and got rectification parameters thanks to you. Thing is when I try to rectification it gives wrong images. 
As first, you can find the code here: 
https://github.com/aliyasineser/FisheyeStereoDepth/blob/master/undistortion.cpp

Just ignore the disparity image, it is bad already. Rectification is number one problem. The original images:
![left_0](https://user-images.githubusercontent.com/11279720/45739144-7ab59380-bbf2-11e8-94f7-95f26d98f417.png)
![right_0](https://user-images.githubusercontent.com/11279720/45739145-7ab59380-bbf2-11e8-8c22-096bb440074f.png)

Rectification(!) and disparity images:
![screenshot from 2018-09-18 17-30-46](https://user-images.githubusercontent.com/11279720/45739095-5d80c500-bbf2-11e8-9e20-1df2e0c96749.png)

Thanks for helping.

**Comment by sourishg** [comment]
Hi @aliyasineser. Maybe the calibration isn't done correctly. Clearly, the rectification is wrong. Check if all the parameters are correct. Also, during calibration, check if the chessboard corners are being detected properly to ensure proper calibration.

**Comment by aliyasineser** [comment]
To undistort without rectify, I use the same functions but I don't give R and P so I can see the calibration is right or not. It looks okay but when  R and P parameters added it looks like this. My reprojection error from stereoCalibrate sometimes comes -nan and sometimes 1.4 or so. I reduced the pictures and my error rate reduced. I think I need new dataset for calibration, I will make it. If still not correct, I hope you can enlighten me about something. I will give you full information, anything you need. Thank you so much for the answer.

**Comment by mt-cly** [comment]
> 
> 
> To undistort without rectify, I use the same functions but I don't give R and P so I can see the calibration is right or not. It looks okay but when R and P parameters added it looks like this. My reprojection error from stereoCalibrate sometimes comes -nan and sometimes 1.4 or so. I reduced the pictures and my error rate reduced. I think I need new dataset for calibration, I will make it. If still not correct, I hope you can enlighten me about something. I will give you full information, anything you need. Thank you so much for the answer.

wow, I get the wrong like you said. It's looks well without R, P. But it's bad with R, P.
Have you resolved this problem? plz.

**Comment by aliyasineser** [comment]
> > To undistort without rectify, I use the same functions but I don't give R and P so I can see the calibration is right or not. It looks okay but when R and P parameters added it looks like this. My reprojection error from stereoCalibrate sometimes comes -nan and sometimes 1.4 or so. I reduced the pictures and my error rate reduced. I think I need new dataset for calibration, I will make it. If still not correct, I hope you can enlighten me about something. I will give you full information, anything you need. Thank you so much for the answer.
> 
> wow, I get the wrong like you said. It's looks well without R, T. But it's bad with R, T.
> Have you resolved this problem? plz.

I couldn't solve the problem. I changed my lenses and decreased the field of view. Since angle is not wide, I managed to do standart calibration instead of fisheye. Unfortunately I can't help you.

**Comment by mt-cly** [comment]
> 
> 
> > > To undistort without rectify, I use the same functions but I don't give R and P so I can see the calibration is right or not. It looks okay but when R and P parameters added it looks like this. My reprojection error from stereoCalibrate sometimes comes -nan and sometimes 1.4 or so. I reduced the pictures and my error rate reduced. I think I need new dataset for calibration, I will make it. If still not correct, I hope you can enlighten me about something. I will give you full information, anything you need. Thank you so much for the answer.
> > 
> > 
> > wow, I get the wrong like you said. It's looks well without R, T. But it's bad with R, T.
> > Have you resolved this problem? plz.
> 
> I couldn't solve the problem. I changed my lenses and decreased the field of view. Since angle is not wide, I managed to do standart calibration instead of fisheye. Unfortunately I can't help you.

Thanks for your reply. That's really confused. And the related information is soooo less.
