### ISSUE TITLE
Question about your stereo calibration method

### ISSUE THREAD

**Issue by lucasyaref** [sourishg/fisheye_stereo#4]
Hi Sourish,

I am working with your code and I was wondering why in this code comparing to standard stereo calibration (your other repository about stereo calibration for narrow_stereo model) you do not use K1, D1, K2, D2 from previous config file. Do you proceed to stereo calibration without the monocular camera being calibrated before ?

Also how do you evaluate your stereo calibration method. I mean myself I ouput the rms returned by stereoCalibrate. However in your monoCalibration method you use recomputereprojectionErrors() function. Is it possible to do it in stereo vision ?
I ask this question because I use this function in order to delete images that are toxic to my calibration by using the criteria of perViewErrors.

I am very thankful however for your hard work and your code is really easy to understand/modify.
Best regards,
FERAY Lucas.

**Comment by sourishg** [comment]
@lucasyaref you can re-use the intrinsics from the monocular calibration during stereo. That is a perfectly fine option and often the recommended one. And yes, you can also use reprojection errors to validate your calibration performance. Sorry, I don't maintain this repo now so you'd have to do the implementation on your own but it should be pretty simple.

**Comment by lucasyaref** [comment]
@sourishg Yes totally I do not wish to take much of your time. 
Thank you for the answer I will work on it, again thank you for your hard work.
